# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               EVE
tagline:             'a light life'
description:         '一个技术博客'
url:                 https://cocoakekeyu.github.io/
baseurl:             ''
gems: [jekyll-paginate]
paginate:            5
paginate_path: "page:mum"

# About/contact
author:
  name:              EVE
  email:             cocoakekeyu@gmail.com

# Markdown processor
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
